### PR TITLE
Deprecate mistral in reference chapter

### PR DESCRIPTION
**Pull request by winem**
This PR deprecates mistral in the reference chapter and rewords all occurences of mistral and PostgreSQL but one where PostgreSQL is mentioned as optional coordination backend.

This PR will be a draft until I was able to update the diagrams. (@amanda11 and me are already working on it.)

### CODE REVIEW

**Comment by armab** [comment]
Thanks for the work! Referenced it in the https://github.com/StackStorm/st2docs/pull/1010 game plan

**Comment by armab** [comment]
@winem Do you think can we merge it now after https://github.com/StackStorm/st2docs/pull/1016?
If there are more diagrams to update, they can go as a separated PR.

**Comment by winem** [comment]
@armab fine for me. It will be super helpful for the next reviews to get this one merged. I'll update the missing diagram as soon as it's available.

**Review by armab — APPROVED** [review]
Thanks @winem for updating this part of mistral deprecation!

**Pull request merged**
