### PR TITLE
Missing https://

### PR DESCRIPTION
**Pull request by LindsayHill**
Same as #353, applied to v2.1 branch

### CODE REVIEW

**Comment by Kami** [comment]
Good catch - LGTM

**Comment by Kami** [comment]
> ./scripts/clone-st2.sh
> Cloning branch v2.1.1 of st2
> Cloning into 'st2'...

This seems wrongs, this should be a branch, not a tag, looking.

**Comment by Kami** [comment]
`version.txt` looks fine so no idea what is going on.

**Comment by LindsayHill** [comment]
Docs building is a little weird for x.y.z versions. Docs only have x.y.
There is a workflow somewhere that strips .z.

Could be related

**Comment by Kami** [comment]
@LindsayHill This shouldn't matter, it should use version from `version.txt` which is correctly set to `v2.1`, but it some how read `v2.1.1` from somewhere so it got me confused.

**Comment by Kami** [comment]
Fix for the docs version is in https://github.com/StackStorm/st2docs/pull/355.

**Pull request merged**
