### PR TITLE
Point enterprise installation to stable repos

### PR DESCRIPTION
**Pull request by dzimine**

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1457043073005877

**Comment by armab** [comment]
@dzimine @lakshmi-kannan 

I guess this PR is intentional (for future), but just a reminder to be sure: 
We don't have packages in `enterprise` stable yet, only `enterprise` staging.

This should be possible after CI promotion `staging` -> `production`.

**Comment by dzimine** [comment]
I think @lakshmi-kannan or @DoriftoShoes moved them manually, if not, we should. 
This is driven by the fact that the same access key can not work for both `enterprise` and `enterprise-staging`. And because our current approach License==key, each user begins to get new License that opens two locks - old AIO installer download site, and only ONE of package cloud repos, we have to choose. And once chosen, it's not easy to re-issue the key. 
Sorry if the explanation is confusing, we can pick it on slack.

**Comment by armab** [comment]
Yeah, `StackStorm/enterprise` repo is currently empty.

**Comment by lakshmi-kannan** [comment]
@armab I didn't get to move the packages to prod. Can you do that?

**Comment by armab** [comment]
@lakshmi-kannan Sure, I can upload them manually on Monday.

**Comment by armab** [comment]
Seems @lakshmi-kannan already figured it out.
I just uploaded missed packages for `debian wheezy` and `debian jessie`, probably oversight.

**Pull request merged**
