### PR TITLE
Added full path to st2sensorcontainer

### PR DESCRIPTION
**Pull request by LindsayHill**
Addresses https://github.com/StackStorm/st2docs/issues/306

### CODE REVIEW

**Comment by Kami** [comment]
IIRC, we symlink all the components to `/usr/bin` / `/usr/local/bin` so if it's not in $PATH it must be some other issue.

In general I'm fine with this change as long as it's consistent everywhere and as long as we try to figure out why it wasn't originally in $PATH.

**Comment by LindsayHill** [comment]
Mmmm, that's an interesting point actually about $PATH. It clearly wasn't in that user's path, and I've seen other reports of something similar. I might have a quick look around some test systems before merging this.

**Comment by armab** [comment]
Just checked, and there is no `st2sensorcontainer` in `/usr/local/bin`, here is the full list:
https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2.links

So the PR looks good. Probably confused with `service st2sensorcontainer`.


If we need `st2sensorcontainer` in `$PATH` - we can add it, but not sure if that's needed, considering its "debugging" nature.

**Comment by Kami** [comment]
@armab Yeah, I was wrong and you are right - we only symlink the tools but not the actual services.

In this case @LindsayHill change is good and we should do the same everywhere else. Another option is to also symlink the services.

What do other people think?

**Comment by armab** [comment]
From the other side, `st2-rule-tester` is already there: https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/st2.links#L4 which is for debugging purposes :)

**Comment by Kami** [comment]
@armab true, but rule-tester is a script (tool) and not a long living service.

Anyways :)

**Comment by armab** [comment]
@kami Ah right, got it :+1:

**Pull request merged**
