### PR TITLE
Add description for new regex and iregex operators. Deprecate matchregex.

### PR DESCRIPTION
**Pull request by pixelrebel**
Documentation update related to this pull request: https://github.com/StackStorm/st2/pull/2558

### CODE REVIEW

**Comment by Kami** [comment]
Merged, thanks.

**Comment by pixelrebel** [comment]
@Kami Sorry, I just noticed a markdown typo: https://github.com/pixelrebel/st2docs/commit/51a99d4397fb30117424de6192c5611abee31baa#diff-472d3d450cddf45eda0cfde2ab028b48R21

I fixed in my branch, do I need to resubmit a new PR?

**Comment by Kami** [comment]
It's fine, I actually already fixed it locally and pushed those changes to master :)

**Comment by pixelrebel** [comment]
Nice, thanks!

**Pull request merged**
