### PR TITLE
Update architecture diagram and StackStorm services page

### PR DESCRIPTION
**Pull request by Kami**
This pull request updates architecture diagram and service page so tit reflects actual / current state (removed st2resultstracker, added st2notifier, st2scheduler, st2workflow engine, added a connection from Mistral back to StackStorm API).

It also adds a link to HA deployment page which describes how services should be configured for HA (which services can have multiple instances, etc.).

### CODE REVIEW

**Comment by Kami** [comment]
Will cherry pick those changes in v3.0 once it's merged.

**Comment by nmaludy** [comment]
This might close #858

**Comment by Kami** [comment]
@LindsayHill microservices :P

**Comment by nmaludy** [comment]
I could be wrong, but should the hubot-stackstorm plugin have lines back to `st2api` and `st2stream`?

**Comment by Kami** [comment]
@nmaludy It should indeed have a link back to st2api and st2stream - good catch :+1:

**Pull request merged**
