### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by cognifloyd**
This updates to the latest version of the theme. I believe I've covered all the edge cases, so the sitemap should work, and the versions menu should be backwards compatible (though we need to double check the versions menu once this is merged to be safe).

### CODE REVIEW

**Comment by cognifloyd** [comment]
Ok. I've verified that this maintains the versions menu for older versions and I think I've fixed the sitemap. So this should be ready to merge.

I have not removed the old forked theme, we can do that in a follow up once we're satisfied nothing else is missing.

**Comment by cognifloyd** [comment]
This does not as read the docs - it only updates the theme

**Review by mamercad — APPROVED** [review]
🚀

**Comment by cognifloyd** [comment]
so, readthedocs is expected to fail - I will follow up after this PR with the bits that allow it to build PRs.

**Review by rush-skills — APPROVED** [review]

**Pull request merged**
