### PR TITLE
remove extra comma from json

### PR DESCRIPTION
**Pull request by punkrokk**
The current json for the example Graphite Dashboard has a comma after width in each section which is invalid JSON. I update the json to it works by removing the commas.

### CODE REVIEW

**Comment by armab** [comment]
@punkrokk Looks like CI is not happy with these changes.

**Comment by punkrokk** [comment]
Pushed EOF New line. Should pass in a moment

**Comment by punkrokk** [comment]
pushed EOF New line, should pass shortly

**Comment by punkrokk** [comment]
@armab Fixed, you'll see in the changes what I had to do.

**Pull request merged**
