### PR TITLE
Migrate to Sphinx2 and Python3

### PR DESCRIPTION
**Pull request by LindsayHill**

### CODE REVIEW

**Comment by LindsayHill** [comment]
@Kami this is now working, and builds docs using Sphinx2 + Python3. The published artifacts look OK - e.g. see here https://1870-49105003-gh.circle-artifacts.com/0/st2docs/index.html

Could you cast your eye over it, see what you think?

**Comment by LindsayHill** [comment]
Related PR here https://github.com/StackStorm/ipfabric-docs/pull/159

I think this one needs to be merged before that one will pass CI

**Comment by Kami** [comment]
LGTM, but haven't tried it locally yet.

**Comment by Kami** [comment]
Same as in other repo - https://github.com/StackStorm/ipfabric-docs/pull/159#issuecomment-487097591

To be on the safe side, we should update cache key.

**Comment by LindsayHill** [comment]
Going to pull in a punch of sphinx_rtd_theme updates into this before merging. We diverged from upstream a while back, and there's a lot of updates. Better to combine them with sphinx2, as there's mutual dependencies there.

**Comment by LindsayHill** [comment]
Decided to get Sphinx + Py3 done as one change, will do further theme changes as separate PRs

**Pull request merged**
