### PR TITLE
Change default user

### PR DESCRIPTION
**Pull request by enykeev**
STORM-2036

### CODE REVIEW

**Comment by dzimine** [comment]
There gotta be a correspondent changes in the bootstrap scripts in st2-packages, can you please cover?

**Comment by enykeev** [comment]
Already. https://github.com/StackStorm/st2-packages/pull/212 and https://github.com/StackStorm/st2chatops/pull/19

**Comment by lakshmi-kannan** [comment]
lgtm. What about v1.3 branch? +1 to merge this to bootstrap scripts and chatops.env

**Comment by enykeev** [comment]
Considering how much stuff we already backported to 1.3, I don't really see a problem merging this commits too.

**Pull request merged**
