### PR TITLE
Update walk-through taking into account new schema checks

### PR DESCRIPTION
**Pull request by warrenvw**
Initialize git repo at `/opt/stackstorm/packs/hello_st2`, not just `hello_st2`.

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1495570625434380

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1495570731480161

**Comment by bigmstone** [comment]
@warrenvw I believe the new changes look good, but will you confirm this walk-through works on 2.2.1? Specifically that if an empty `config.yaml` exists that it won't fall over?

**Comment by warrenvw** [comment]
Yes, I tested in st2-docker. Here's the transcript:

```
root@e9cdba372a08:~/hello_st2# st2 --version
st2 2.2.1
root@e9cdba372a08:~/hello_st2# st2 pack install file:///$PWD

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+--------------------------------------------------------------+
| Property    | Value                                                        |
+-------------+--------------------------------------------------------------+
| name        | Hello StackStorm                                             |
| description | A simple pack containing examples of sensor, rule, and       |
|             | action.                                                      |
| version     | 0.1.0                                                        |
| author      | st2-dev                                                      |
+-------------+--------------------------------------------------------------+
root@e9cdba372a08:~/hello_st2# touch config.schema.yaml
root@e9cdba372a08:~/hello_st2# git add config.schema.yaml 
root@e9cdba372a08:~/hello_st2# git commit -m "touch config.schema.yaml"
[master 4a7aa1c] touch config.schema.yaml
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 config.schema.yaml
root@e9cdba372a08:~/hello_st2# st2 pack install file:///$PWD

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[  failed   ] register pack

id: 5925f4d24cd9de154e1b0a6f
action.ref: packs.install
parameters: 
  packs:
  - file:////root/hello_st2
status: failed
error: st2.actions.python.St2RegisterAction: DEBUG    Calling client method "register" with kwargs "{'types': ['action', 'alias', 'sensor', 'trigger'], 'packs': [u'hello_st2']}"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 76, in run
    format_func=format_result)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 144, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 443, in register
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request
MESSAGE: Failed to register pack "hello_st2": Config schema "/opt/stackstorm/packs/hello_st2/config.schema.yaml" is empty and invalid. for url: http://0.0.0.0:9101/v1/packs/register

traceback: None
failed_on: register pack
start_timestamp: 2017-05-24T21:02:10.235745Z
end_timestamp: 2017-05-24T21:02:21.288556Z
+--------------------------+------------------------+---------------------------+-------------------------+-------------------------------+
| id                       | status                 | task                      | action                  | start_timestamp               |
+--------------------------+------------------------+---------------------------+-------------------------+-------------------------------+
| 5925f4d24cd9de0097694d22 | succeeded (2s elapsed) | download pack             | packs.download          | Wed, 24 May 2017 21:02:10 UTC |
| 5925f4d44cd9de0097694d24 | succeeded (1s elapsed) | make a prerun             | packs.virtualenv_prerun | Wed, 24 May 2017 21:02:12 UTC |
| 5925f4d54cd9de0097694d27 | succeeded (5s elapsed) | install pack dependencies | packs.setup_virtualenv  | Wed, 24 May 2017 21:02:13 UTC |
| 5925f4db4cd9de0097694d29 | failed (1s elapsed)    | register pack             | packs.load              | Wed, 24 May 2017 21:02:19 UTC |
+--------------------------+------------------------+---------------------------+-------------------------+-------------------------------+
root@e9cdba372a08:~/hello_st2# git revert HEAD
[master 8d6e338] Revert "touch config.schema.yaml"
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 config.schema.yaml
root@e9cdba372a08:~/hello_st2# st2 pack install file:///$PWD

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+--------------------------------------------------------------+
| Property    | Value                                                        |
+-------------+--------------------------------------------------------------+
| name        | Hello StackStorm                                             |
| description | A simple pack containing examples of sensor, rule, and       |
|             | action.                                                      |
| version     | 0.1.0                                                        |
| author      | st2-dev                                                      |
+-------------+--------------------------------------------------------------+
```

**Comment by warrenvw** [comment]
And adding an empty config.yaml:

```
root@e9cdba372a08:~/hello_st2# git add config.yaml
root@e9cdba372a08:~/hello_st2# git commit -m "Add empty config.yaml"
[master 54fe236] Add empty config.yaml
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 config.yaml
root@e9cdba372a08:~/hello_st2# 
root@e9cdba372a08:~/hello_st2# st2 pack install file:///$PWD

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+--------------------------------------------------------------+
| Property    | Value                                                        |
+-------------+--------------------------------------------------------------+
| name        | Hello StackStorm                                             |
| description | A simple pack containing examples of sensor, rule, and       |
|             | action.                                                      |
| version     | 0.1.0                                                        |
| author      | st2-dev                                                      |
+-------------+--------------------------------------------------------------+
root@e9cdba372a08:~/hello_st2# ls -al
total 36
drwxr-xr-x 8 root root 4096 May 24 22:41 .
drwx------ 5 root root 4096 May 24 22:41 ..
drwxr-xr-x 8 root root 4096 May 24 22:41 .git
drwxr-xr-x 2 root root 4096 May 24 19:28 actions
drwxr-xr-x 2 root root 4096 May 24 19:29 aliases
-rw-r--r-- 1 root root    0 May 24 22:41 config.yaml
-rw-r--r-- 1 root root  211 May 24 19:27 pack.yaml
drwxr-xr-x 2 root root 4096 May 24 19:29 policies
-rw-r--r-- 1 root root    0 May 24 19:26 requirements.txt
drwxr-xr-x 2 root root 4096 May 24 19:28 rules
drwxr-xr-x 2 root root 4096 May 24 19:28 sensors
```

**Comment by LindsayHill** [comment]
@warrenvw this PR only seems to have changes for the second commit, not the first one related to hello_st2 location. Is that intentional?

**Pull request merged**
