### PR TITLE
Include tag / revision argument in the installer install command

### PR DESCRIPTION
**Pull request by Kami**
The title says it all.

### CODE REVIEW

**Comment by Kami** [comment]
@manasdk Can you get this published once it's merged?

**Comment by manasdk** [comment]
Go ahead and merge the publish is automated

**Comment by manasdk** [comment]
:+1: 

Definitely an oversight. Thanks for the change.

**Comment by Kami** [comment]
> Go ahead and merge the publish is automated

Magic!

**Pull request merged**
