### PR TITLE
Improved examples in sensor doc

### LINKED ISSUE #470: Sensor documentation should be improved to have real working sensors
jeremybr on slack:

https://docs.stackstorm.com/sensors.html#creating-a-sensor shows a blank class as the sample sensor impl. I can just look in the installed packs but I would fix this. the SamplePollingSensor is blank too.

### PR DESCRIPTION
**Pull request by LindsayHill**
Improved some of the example sensor docs

Cleaned up a little bit of language.

Sensors doc probably still needs complete overhaul

Fixes #470

### CODE REVIEW

**Comment by Kami** [comment]
:+1:

**Comment by LindsayHill** [comment]
Gah. It's not even my change that's breaking builds!
> Warning, treated as error:
> st2/CHANGELOG.rst:113: ERROR: Unexpected indentation.

**Comment by Kami** [comment]
@LindsayHill Thanks, will look into a fix.

**Comment by LindsayHill** [comment]
https://github.com/StackStorm/st2/pull/3471

**Pull request merged**
