### PR TITLE
Install chatops package

### PR DESCRIPTION
**Pull request by manasdk**
Done on ubuntu but not on rhel.

Unsure if this step is needed but it would seem that this is correct.

### CODE REVIEW

**Comment by manasdk** [comment]
Based on https://github.com/StackStorm/st2-packages/blob/470a32582e64cbdc5222f3b7b0271d38fae775b5/scripts/st2bootstrap-el6.sh#L201 it would seem I am correct.

**Comment by dzimine** [comment]
Oh... I can't believe we missed it. Thank you!

**Comment by dzimine** [comment]
Can you pls cherrypick to v1.3, too?

**Comment by manasdk** [comment]
cherrypick https://github.com/StackStorm/st2docs/pull/95

**Pull request merged**
